version: "3.8"

services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: changemeinprod
      # Thêm biến môi trường giới hạn bộ nhớ
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 32MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 256MB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    command: start-dev
    restart: always
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: changemeinprod
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      # Thêm cấu hình JVM
      JAVA_OPTS: "-Xms64m -Xmx256m -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -XX:+UseG1GC"
    depends_on:
      - postgres
    networks:
      - local
    volumes:
      - keycloak_data:/opt/keycloak/data
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 128M

volumes:
  postgres_data:
  keycloak_data:
networks:
  local:
    driver: bridge