version: "3.8"
services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: changemeinprod
      # Các tham số PostgreSQL được tối ưu nhưng không giới hạn cứng
      POSTGRES_SHARED_BUFFERS: 512MB
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_MAINTENANCE_WORK_MEM: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    command: start-dev
    restart: always
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: changemeinprod
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      # Cấu hình JVM tối ưu không giới hạn heap size cứng
      JAVA_OPTS: >-
        -XX:+UseG1GC 
        -XX:MaxGCPauseMillis=100 
        -XX:+ParallelRefProcEnabled 
        -XX:+HeapDumpOnOutOfMemoryError 
        -XX:HeapDumpPath=/opt/keycloak/data/heapdump
    depends_on:
      - postgres
    networks:
      - local
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  keycloak_data:
networks:
  local:
    driver: bridge